// Programming languages with their corresponding Devicon class names
export const programmingLanguages = [
    { name: "JavaScript", icon: "devicon-javascript-plain colored" },
    { name: "Python", icon: "devicon-python-plain colored" },
    { name: "Java", icon: "devicon-java-plain colored" },
    { name: "TypeScript", icon: "devicon-typescript-plain colored" },
    { name: "C++", icon: "devicon-cplusplus-plain colored" },
    { name: "C#", icon: "devicon-csharp-plain colored" },
    { name: "PHP", icon: "devicon-php-plain colored" },
    { name: "Ruby", icon: "devicon-ruby-plain colored" },
    { name: "Swift", icon: "devicon-swift-plain colored" },
    { name: "Go", icon: "devicon-go-plain colored" },
    { name: "Rust", icon: "devicon-rust-plain colored" },
    { name: "Kotlin", icon: "devicon-kotlin-plain colored" },
    { name: "R", icon: "devicon-r-plain colored" },
    { name: "Dart", icon: "devicon-dart-plain colored" },
    { name: "Scala", icon: "devicon-scala-plain colored" },
    { name: "Elixir", icon: "devicon-elixir-plain colored" },
    { name: "Clojure", icon: "devicon-clojure-plain colored" },
    { name: "Haskell", icon: "devicon-haskell-plain colored" },
    { name: "HTML", icon: "devicon-html5-plain colored" },
    { name: "CSS", icon: "devicon-css3-plain colored" },
    { name: "SCSS", icon: "devicon-sass-plain colored" },
    { name: "Shell", icon: "devicon-bash-plain colored" },
    { name: "Perl", icon: "devicon-perl-plain colored" },
    { name: "Lua", icon: "devicon-lua-plain colored" },
    { name: "Vue", icon: "devicon-vuejs-plain colored" },
    { name: "React", icon: "devicon-react-plain colored" },
    { name: "Angular", icon: "devicon-angularjs-plain colored" },
    { name: "Django", icon: "devicon-django-plain colored" },
    { name: "Flask", icon: "devicon-flask-plain colored" },
    { name: "Laravel", icon: "devicon-laravel-plain colored" },
    { name: "Spring", icon: "devicon-spring-plain colored" },
    { name: "Docker", icon: "devicon-docker-plain colored" },
    { name: "Kubernetes", icon: "devicon-kubernetes-plain colored" },
    { name: "MongoDB", icon: "devicon-mongodb-plain colored" },
    { name: "PostgreSQL", icon: "devicon-postgresql-plain colored" },
    { name: "MySQL", icon: "devicon-mysql-plain colored" },
    { name: "Redis", icon: "devicon-redis-plain colored" },
    { name: "GraphQL", icon: "devicon-graphql-plain colored" },
    { name: "Markdown", icon: "devicon-markdown-plain" },
    { name: "Jupyter Notebook", icon: "devicon-jupyter-plain colored" },
    { name: "Assembly", icon: "fas fa-microchip" }, // Using Font Awesome for languages without Devicon
    { name: "MATLAB", icon: "fas fa-square-root-alt" },
    { name: "Objective-C", icon: "fab fa-apple" },
    { name: "Vim script", icon: "devicon-vim-plain colored" },
    { name: "WebAssembly", icon: "fas fa-cube" }
];
